version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fhir_app
    environment:
      NODE_ENV: production
      EXTERNAL_FHIR_URL: 'https://server.fire.ly/r4'
    ports:
      - "3000:3000"
    restart: unless-stopped