name: Deploy to servak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t webapp:latest .
          docker save -o app.tar.gz webapp:latest

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.ORANGE_PI_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          set -e
          set -x
          ssh -i ~/.ssh/id_ed25519 -o ServerAliveInterval=60 -p ${{ secrets.ORANGE_PI_PORT }} \
            ${{ secrets.ORANGE_PI_USER }}@${{ secrets.ORANGE_PI_IP }} << 'EOF'
            set -e
          
            mkdir -p ~/fhir-app
          
            tar xzf /tmp/fhir-app.tar.gz -C ~/fhir-app
          
            cd ~/fhir-app
          
            docker stop node_app
            docker rm node_app
          
            docker stop fhir_app || true
            docker rm fhir_app || true
          
            docker build -t fhir-app:latest .
            docker run -d --name fhir_app \
              -p 80:3000 \
              -e NODE_ENV=production \
              -e EXTERNAL_FHIR_URL='https://server.fire.ly/r4' \
              --restart unless-stopped \
              fhir-app:latest
          
            docker ps | grep fhir_app
          EOF
